version: '3.5'

services:
  app:
    build: .
    working_dir: /app
    container_name: happy-backend
    env_file: .env
    volumes:
      - .:/app:delegated
      - ./node_modules:/app/node_modules
      - ~/.ssh:/root/.ssh
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3008:3000

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: Asia/Bangkok
    ports:
      - 5432:5432
    volumes:
      - ./postgresData:/var/lib/postgresql/data

volumes:
  postgresData: